// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwW99aIhg5xJkQmu59KCKX2TXCGqXfNTs',
    appId: '1:329570339285:web:606864f0d168dccfc5155c',
    messagingSenderId: '329570339285',
    projectId: 'proyecto-b1a16',
    authDomain: 'proyecto-b1a16.firebaseapp.com',
    storageBucket: 'proyecto-b1a16.firebasestorage.app',
    measurementId: 'G-6GHXDZPR3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASXgVBzWL4vSCyEVPJMtqfT9SkeiqwzkI',
    appId: '1:329570339285:android:640d1c7ee12965d2c5155c',
    messagingSenderId: '329570339285',
    projectId: 'proyecto-b1a16',
    storageBucket: 'proyecto-b1a16.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwW99aIhg5xJkQmu59KCKX2TXCGqXfNTs',
    appId: '1:329570339285:web:9c63ccd7d9bf2dd2c5155c',
    messagingSenderId: '329570339285',
    projectId: 'proyecto-b1a16',
    authDomain: 'proyecto-b1a16.firebaseapp.com',
    storageBucket: 'proyecto-b1a16.firebasestorage.app',
    measurementId: 'G-RPQ6T19GMR',
  );

}